# Generated by Django 3.1.3 on 2020-12-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('renda', models.FloatField()),
                ('pais', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.pessoa')),
            ],
            options={
                'verbose_name_plural': 'Solicitações',
            },
        ),
    ]
