# Generated by Django 3.1.3 on 2020-12-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=250)),
                ('cep', models.CharField(max_length=8)),
                ('bairro', models.CharField(max_length=250)),
                ('rua', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='rua',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.endereco'),
            preserve_default=False,
        ),
    ]
