# Generated by Django 3.1.3 on 2020-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_pessoa_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='credito',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='renda',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='score',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='credito',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='renda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
