# Generated by Django 3.1.3 on 2020-12-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20201212_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='Api.pessoa'),
        ),
    ]
